// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: triage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TriageService_AnalyzeSymptoms_FullMethodName = "/chestpain.TriageService/AnalyzeSymptoms"
)

// TriageServiceClient is the client API for TriageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TriageServiceClient interface {
	AnalyzeSymptoms(ctx context.Context, in *SymptomInput, opts ...grpc.CallOption) (*TriageResponse, error)
}

type triageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTriageServiceClient(cc grpc.ClientConnInterface) TriageServiceClient {
	return &triageServiceClient{cc}
}

func (c *triageServiceClient) AnalyzeSymptoms(ctx context.Context, in *SymptomInput, opts ...grpc.CallOption) (*TriageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriageResponse)
	err := c.cc.Invoke(ctx, TriageService_AnalyzeSymptoms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriageServiceServer is the server API for TriageService service.
// All implementations must embed UnimplementedTriageServiceServer
// for forward compatibility.
type TriageServiceServer interface {
	AnalyzeSymptoms(context.Context, *SymptomInput) (*TriageResponse, error)
	mustEmbedUnimplementedTriageServiceServer()
}

// UnimplementedTriageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTriageServiceServer struct{}

func (UnimplementedTriageServiceServer) AnalyzeSymptoms(context.Context, *SymptomInput) (*TriageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeSymptoms not implemented")
}
func (UnimplementedTriageServiceServer) mustEmbedUnimplementedTriageServiceServer() {}
func (UnimplementedTriageServiceServer) testEmbeddedByValue()                       {}

// UnsafeTriageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriageServiceServer will
// result in compilation errors.
type UnsafeTriageServiceServer interface {
	mustEmbedUnimplementedTriageServiceServer()
}

func RegisterTriageServiceServer(s grpc.ServiceRegistrar, srv TriageServiceServer) {
	// If the following call pancis, it indicates UnimplementedTriageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TriageService_ServiceDesc, srv)
}

func _TriageService_AnalyzeSymptoms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymptomInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriageServiceServer).AnalyzeSymptoms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TriageService_AnalyzeSymptoms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriageServiceServer).AnalyzeSymptoms(ctx, req.(*SymptomInput))
	}
	return interceptor(ctx, in, info, handler)
}

// TriageService_ServiceDesc is the grpc.ServiceDesc for TriageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TriageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chestpain.TriageService",
	HandlerType: (*TriageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSymptoms",
			Handler:    _TriageService_AnalyzeSymptoms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "triage.proto",
}
